### ISSUE TITLE
Weird fast auto incrementing. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#13]
You might have to either reset it or subtract out scores a little. (Let me have a day 😝 )

*_\*\*\*jcgter777 runs_*

**Comment by ticalc-travis** [comment]
I wonder if there could be a rare condition that gets triggered when multiple people press the button right at the same moment, or something like that. It seems like it tends to happen when there's a lot of heavy activity going on at once.

**Comment by josheewa** [comment]
It happened for me when only I was on.

**Comment by josheewa** [comment]
I think it's good now.
