### ISSUE TITLE
Maybe enlarge the hovered over name on the LB?

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#24]

**Comment by Legend-of-iPhoenix** [comment]
This is possible using CSS only.

Because you are relatively new to the language, I think it would be a good exercise for you in CSS selectors.

**Comment by josheewa** [comment]
Whoo! CHALLENGE!!!

**Comment by josheewa** [comment]
I'm going to use Google!!! So cool!

<sup><sub>*edit by \_iPhoenix\_: what is this madness?!*</sub></sup> I dunno, why?

**Comment by Legend-of-iPhoenix** [comment]
Completed in https://github.com/Legend-of-iPhoenix/TheButton/commit/0b52f5624eb87faae8f60346b0bbb2a50b9988ff

**Comment by josheewa** [comment]
What? it's not completed?
@Legend-of-iPhoenix
