### ISSUE TITLE
I'm adding a favicon, but I need to add it to the "root of the site" how do I do that?

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#30]
This is a question. 
Favicon package:
[favicon_package_v0.16.zip](https://github.com/Legend-of-iPhoenix/TheButton/files/1798897/favicon_package_v0.16.zip)

Code:
`<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">`

Link: 
[https://realfavicongenerator.net/favicon_result?file_id=p1c86mijanm8gcl11b3vh6e1j006#.WqMt7r3wYng](url)

**Comment by Legend-of-iPhoenix** [comment]
What kind of crappy software are you using? Just create a .png file, and follow the [official spec](https://www.w3.org/2005/10/howto-favicon)
