### ISSUE TITLE
Sometimes it says 0, 0, and 0, but sometimes when someone else presses, it says now. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#4]
That is, when someone just clicked it. maybe a glitch in the time database thing

**Comment by Legend-of-iPhoenix** [comment]
This is also another side effect of the bug mentioned in my Cemetech post.

**Comment by josheewa** [comment]
Uhhh what post? @Legend-of-iPhoenix
