### ISSUE TITLE
When I spam the button, my time on the leaderboard decreases by 1 sec each time. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#5]

**Comment by jcgter777** [comment]
Times change on the leaderboard, annoying

**Comment by JonathanBush** [comment]
My time decreases even when I am not spamming the button.

**Comment by josheewa** [comment]
Just pressing it? Weird. If I spam it, it decreases, slowly.

**Comment by JonathanBush** [comment]
It specifically happens when someone else clicks the button very shortly after I have clicked it.

**Comment by Legend-of-iPhoenix** [comment]
This is a side effect of the thing mentioned in my Cemetech post.

**Comment by josheewa** [comment]
Uhhhh, what post? @Legend-of-iPhoenix
