### ISSUE TITLE
Cursor flashes at the edge of the button

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#60]

**Comment by josheewa** [comment]
Whoo hoo! Time to GOOGLE!!!

**Comment by josheewa** [comment]
I think I fixed it in my repo. It doesn't flash, but also doesn't move when you hover. Easy fix. It looks weird that it moved when hovering, and then moves again when clicking. The cursor changing is enough in my opinion. Just in case, I left the old code there enclosed with /* and */. It looks good to me, though. _But_, there needs to be more for the animation of the click now. 

@Legend-of-iPhoenix and @ticalc-travis 

EDIT: NEW IDEA!!! When you hover, have it just have a shadow, and not move? I'm doing that in my repo, but keeping everything else.

**Comment by ticalc-travis** [comment]
I agree with just taking away the moving thing.

No need to comment it out, though—that's why we have a commit history :-) Just delete it; if we need it again it's in the history

**Comment by josheewa** [comment]
I made the glitch less noticeable in my repo. I think it's good to leave it there. It looks cool!

**Comment by Legend-of-iPhoenix** [comment]
Fixed.

**Comment by josheewa** [comment]
@Legend-of-iPhoenix It's definitely still there, Now, it's at the bottom where it flashes.

**Comment by Legend-of-iPhoenix** [comment]
Yeah, there's nothing we can do about this.
