### ISSUE TITLE
Reloading multiple times causes you to get "signed out"

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#62]
If I press Sign In with Google, it goes to about:blank, and freezes. If I close it, it goes back to normal.

**Comment by Legend-of-iPhoenix** [comment]
It thinks your session is over so it signs you out.

We can disable that though.

**Comment by josheewa** [comment]
@Legend-of-iPhoenix Can I try to make a login/out feature with your help?
