### ISSUE TITLE
Inconsistent colored letter motion.

### ISSUE THREAD

**Issue by JonathanBush** [Legend-of-iPhoenix/TheButton#63]
The motion of the colored letters in "Click me." is not consistent. It appears to glitch every cycle, instead of smoothly continuing.

**Comment by josheewa** [comment]
I noticed that too. It does that every second, as far as I can tell. I remember mentioning it before, though...

**Comment by Legend-of-iPhoenix** [comment]
Yeah, that's a problem with my script. It's easily fixed.

I don't remember you mentioning it before, though, @jcgter777.

**Comment by Legend-of-iPhoenix** [comment]
Fixed!

**Comment by josheewa** [comment]
@Legend-of-iPhoenix I thought I said that on IRC. But you said it was fine
