### ISSUE TITLE
Sometimes your click lags, and the other person's time still counts up, and then your's suddenly pops in, and it jumpes a few seconds

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#65]
I'm not sure if the "other" person gets that amount, though.

**Comment by Legend-of-iPhoenix** [comment]
What?

**Comment by ticalc-travis** [comment]
I think I've noticed that. Maybe just a consequence of Internet lag at times (or even browser lag)?

**Comment by Legend-of-iPhoenix** [comment]
Definitely internet lag.

**Comment by josheewa** [comment]
For example, tev has 20 seconds. I click, it lags, and tev gets to 23 seconds. Then, my timer pops up as 2 seconds. 

EDIT: yeah probably just internet lag.

**Comment by Legend-of-iPhoenix** [comment]
This is also due to your system clock being off

The time shown in the `#label` div is calculated locally to conserve server resources, while the time sent to the DB is not.

**Comment by josheewa** [comment]
Makes sense.
