### ISSUE TITLE
There NEEDS to be allowance for bigger font. The button's text is too small, IMO. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/TheButton#66]

**Comment by ticalc-travis** [comment]
What's stopping us? I made it a little bigger in my fork because I also happened to think it was a little small :) https://github.com/ticalc-travis/TheButton/commit/8c0845b00b13533bbf2e7c1fa16dea943a6b7196

**Comment by josheewa** [comment]
Thanks! @Legend-of-iPhoenix
